### PR TITLE
setup dotenv

### PR DESCRIPTION
**Pull request by MillieNakiganda**
#### What does this PR do?
- Adds the library for managing environment variables.
#### Description of Task to be completed?

- Install and setup dotenv for the API to manage environment variables. Ensure packages like - sequelize and passport among the rest can fetch data about the current environment correctly via dotenv. Add documentation on how to utilize dotenv in the API.
#### How should this be manually tested?
- Clone the repo and check through the dependencies in the package.json file

#### Story ID
- [171110040](https://www.pivotaltracker.com/story/show/171110040)

### CODE REVIEW

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Thanks for the effort you have put it. However, I don't think we need Pipfile and pipfile.lock files. I've also failed to trace the dotenv library in your requirements.txt. You ought to install python-dotenv file

**Comment by MillieNakiganda** [comment]
> Thanks for the effort you have put it. However, I don't think we need Pipfile and pipfile.lock files. I've also failed to trace the dotenv library in your requirements.txt. You ought to install python-dotenv file

python-dotenv has been installed, i'll put the pipfile and pipfile.lock in the .gitignore and also update the requirements file. but it has been installed

**Comment by nkalyesubula** [comment]
> > Thanks for the effort you have put it. However, I don't think we need Pipfile and pipfile.lock files. I've also failed to trace the dotenv library in your requirements.txt. You ought to install python-dotenv file
> 
> python-dotenv has been installed, i'll put the pipfile and pipfile.lock in the .gitignore and also update the requirements file. but it has been installed

I can see they python-dotenv file. @MillieNakiganda, Could we also have a meaningful PR description? You can use this [link](https://github.com/andela/anbu-cfh/wiki/Pull-Request-Naming-and-Description-Convention) to guide you come up with one. In the same regard, please ensure that your commit messages are linked with the pivotal tracker story  you're working on

**Comment by MillieNakiganda** [comment]
> > > Thanks for the effort you have put it. However, I don't think we need Pipfile and pipfile.lock files. I've also failed to trace the dotenv library in your requirements.txt. You ought to install python-dotenv file
> > 
> > 
> > python-dotenv has been installed, i'll put the pipfile and pipfile.lock in the .gitignore and also update the requirements file. but it has been installed
> 
> I can see they python-dotenv file. @MillieNakiganda, Could we also have a meaningful PR description? You can use this [link](https://github.com/andela/anbu-cfh/wiki/Pull-Request-Naming-and-Description-Convention) to guide you come up with one. In the same regard, please ensure that your commit messages are linked with the pivotal tracker story you're working on

I will keep the PR naming in mind the next time I request for one.

**Comment by nkalyesubula** [comment]
> > > > Thanks for the effort you have put it. However, I don't think we need Pipfile and pipfile.lock files. I've also failed to trace the dotenv library in your requirements.txt. You ought to install python-dotenv file
> > > 
> > > 
> > > python-dotenv has been installed, i'll put the pipfile and pipfile.lock in the .gitignore and also update the requirements file. but it has been installed
> > 
> > 
> > I can see they python-dotenv file. @MillieNakiganda, Could we also have a meaningful PR description? You can use this [link](https://github.com/andela/anbu-cfh/wiki/Pull-Request-Naming-and-Description-Convention) to guide you come up with one. In the same regard, please ensure that your commit messages are linked with the pivotal tracker story you're working on
> 
> I will keep the PR naming in mind the next time I request for one.

You can still edit your PR. Also make sure you include the story ID in your commit message

**Review by nkalyesubula — COMMENTED** [review]
Thanks for the improvements you have so far made. However, I have realized you deleted all the libraries you found in the codebase. Please put them back. Each of them is useful and we'll be used in the subsequent tasks that you'll be working upon.
Also, correct your git branch naming, make sure you squash your commit messages into 1,and finally ensure that you have a PR title. Please use this [link](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices) to guide you through this

**Comment by MillieNakiganda** [comment]
> Thanks for the improvements you have so far made. However, I have realized you deleted all the libraries you found in the codebase. Please put them back. Each of them is useful and we'll be used in the subsequent tasks that you'll be working upon.
> Also, correct your git branch naming, make sure you squash your commit messages into 1,and finally ensure that you have a PR title. Please use this [link](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices) to guide you through this

For the libraries, let me install them when I need them, I think that will be a much better learning process.
Heading to the link right now then later make the necessary changes.

**Review by nkalyesubula — APPROVED** [review]

**Pull request merged**
